###############################################################################
## CARGO MAKEFILE
## Rust task runner and build tool.
##
## https://github.com/sagiegurari/cargo-make
## $ cargo install --force cargo-make
## ############################################################################

## https://github.com/watchexec/cargo-watch
## $ cargo make watch
[tasks.watch]
install_crate = "cargo-watch"
command = "cargo"
args = [
    "watch",
    "--clear",
    "--exec", "run",
    "--watch", "src"
]

## https://github.com/xd009642/tarpaulin
## $ cargo make tarpaulin
[tasks.coverage]
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--ignore-tests"]

## https://docs.rs/cargo-audit/latest/cargo_audit/index.html
## $ cargo make audit
[tasks.audit]
install_crate = "cargo-audit"
command = "cargo"
args = ["audit"]

## $ cargo make my_flow
[tasks.my_flow]
dependencies = [
    "tarpaulin",
    "audit",
    # "format",
    # "build",
    # "test"
]
## Create Database
# sqlx database create
[tasks.db_create]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["database", "create"]

## Migrate database
## sqlx migrate run
[tasks.db_migrate]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["migrate", "run"]

[tasks.init_db]
dependencies = ["db_create", "db_migrate"]

# cargo sqlx prepare -- --bin personal_ledger_server
[tasks.sqlx_prepare]
install_crate = "sqlx-cli"
command = "cargo"
args = ["sqlx", "prepare", "--", "--bin", "personal_ledger_server" ]

# $ cargo make docker_image
# docker build --network host --tag personal_ledger_server --file Dockerfile .
[tasks.docker_image]
command = "docker"
args = [
    "build", 
    "--network", "host", 
    "--tag", "personal_ledger_server", 
    "--file", "Dockerfile", 
    "."
]

## $ cargo make build
[tasks.build]
dependencies = [
    "sqlx_prepare",
    "docker_image",
]