# Server settings
server:
  # Runtime environment <Development, Testing, Production>
  env: "Development"
  # API port
  port: 8091
  # API address
  address: "127.0.0.1"
  # API log_level <Error, Warn, Info, Debug, Trace>
  log_level: "Info"

# Postgres database config
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "personal_ledger"