# Server settings
application:
  port: 8091
  host: "127.0.0.1"

# Postgres database config
database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "personal_ledger_dev"
  require_ssl: false

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000